version: '3.7'

networks:
  lnmarkets_umbrel:
    external: true

services:
  lnmarkets:
image: ghcr.io/lnmarkets/umbrel:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 4242:4242
    volumes:
      - /data/lnd/:/lnd:ro
    environment:
      - APP_URL=0.0.0.0
      - LND_IP=172.81.4.20
      - BITCOIN_NETWORK=testnet
    networks:
      - lnmarkets_umbrel
