version: '3.7'

x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: '5m'
    max-file: '5'

networks:
  lnmarkets_umbrel:
    external: true

services:
  api:
    container_name: lnmarkets_umbrel_api
    restart: 'on-failure'
    build:
      context: ..
      dockerfile: ./apps/api/docker/Dockerfile.dev
    ports:
      - 8001:8001
    volumes:
      - ../apps/api/srcs:/usr/src/apps/api/srcs
      - /data/lnd/:/lnd/:ro
    environment:
      - LND_IP=172.81.4.20
      - LND_GRPC_PORT=10009
      - BITCOIN_NETWORK=testnet
    networks:
      - lnmarkets_umbrel

  front:
    container_name: lnmarkets_umbrel_front
    restart: 'on-failure'
    build:
      context: ..
      dockerfile: ./apps/front/docker/Dockerfile.dev
      args:
        - APP_LNMARKETS_PORT=4242
    ports:
      - 3000:3000
    volumes:
      - ../apps/front/src:/usr/src/apps/front/src
      - ../apps/front/public:/usr/src/apps/front/public
      - ../apps/front/postcss.config.js:/usr/src/apps/front/postcss.config.js
      - ../apps/front/tailwind.config.js:/usr/src/apps/front/tailwind.config.js
      - ../apps/front/vite.config.js:/usr/src/apps/front/vite.config.js
      - ../apps/front/index.html:/usr/src/apps/front/index.html
      - ../apps/front/.env.development:/usr/src/apps/front/.env.development
    environment:
      - APP_LNMARKETS_PORT=4242
    networks:
      - lnmarkets_umbrel
