version: '3.7'

x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: '5m'
    max-file: '5'

networks:
  lnmarkets_umbrel:
    external: true

services:
  api:
    container_name: lnmarkets_umbrel_api
    restart: 'on-failure'
    build:
      context: ..
      dockerfile: ./apps/api/docker/Dockerfile.dev
    ports:
      - 8001:4242
    volumes:
      - ../apps/api/src:/usr/src/apps/api/src
      - /data/lnd/:/lnd/:ro
    environment:
      - NODE_ENV=development
      - LND_IP=172.81.4.20
      - BITCOIN_NETWORK=testnet
    networks:
      - lnmarkets_umbrel

  front:
    container_name: lnmarkets_umbrel_front
    restart: 'on-failure'
    build:
      context: ..
      dockerfile: ./apps/front/docker/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ../apps/front/src:/usr/src/apps/front/src
      - ../apps/front/public:/usr/src/apps/front/public
      - ../apps/front/postcss.config.js:/usr/src/apps/front/postcss.config.js
      - ../apps/front/tailwind.config.js:/usr/src/apps/front/tailwind.config.js
      - ../apps/front/vite.config.js:/usr/src/apps/front/vite.config.js
      - ../apps/front/index.html:/usr/src/apps/front/index.html
    environment:
      - NODE_ENV=development
    networks:
      - lnmarkets_umbrel
