x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: '5m'
    max-file: '5'

networks:
  lnmarkets_umbrel_testnet:
    name: lnmarkets_umbrel_testnet
    driver: bridge
    ipam:
      config:
        - subnet: 172.81.4.0/24

services:
  bitcoin_testnet:
    image: vafanassieff/bitcoin:0.21.1
    container_name: lnmarkets_umbrel_testnet_bitcoin
    restart: unless-stopped
    volumes:
      - ./bitcoin.conf:/conf/bitcoin.conf:rw
      - /mnt/crypto/bitcoin/testnet:/bitcoin/.bitcoin
    ports:
      - 18332:18332
      - 18333:18333
      - 38332:38332
      - 38333:38333
    environment:
      - PUID=1000
      - PGID=1000
    command: bitcoind -conf=/conf/bitcoin.conf
    networks:
      lnmarkets_umbrel_testnet:
        ipv4_address: 172.81.4.10
    logging: *default-logging

  lnd:
    image: vafanassieff/lnd:v0.13.1-beta
    container_name: lnmarkets_umbrel_testnet_lnd
    hostname: lnmarkets_umbrel_testnet_lnd
    restart: unless-stopped
    ports:
      - 9735:9735
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./lnd.conf:/conf/lnd.conf
      - /data/lnd/:/lnd/.lnd
    command: lnd --configfile=/conf/lnd.conf
    networks:
      lnmarkets_umbrel_testnet:
        ipv4_address: 172.81.4.20
    logging: *default-logging

  api:
    container_name: lnmarkets_umbrel_testnet_api
    restart: 'on-failure'
    build:
      context: ../..
      dockerfile: ./apps/api/docker/Dockerfile.dev
    ports:
      - 8001:4242
    volumes:
      - ${PWD}/../../apps/api/src:/usr/src/apps/api/src
      - /data/lnd/:/lnd/:ro
    environment:
      - NODE_ENV=development
      - LND_IP=172.81.4.20
      - BITCOIN_NETWORK=testnet
    networks:
      - lnmarkets_umbrel_testnet

  front:
    container_name: lnmarkets_umbrel_testnet_front
    restart: 'on-failure'
    build:
      context: ../..
      dockerfile: ./apps/front/docker/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/../../apps/front/src:/usr/src/apps/front/src
      - ${PWD}/../../apps/front/public:/usr/src/apps/front/public
      - ${PWD}/../../apps/front/postcss.config.js:/usr/src/apps/front/postcss.config.js
      - ${PWD}/../../apps/front/tailwind.config.js:/usr/src/apps/front/tailwind.config.js
      - ${PWD}/../../apps/front/vite.config.js:/usr/src/apps/front/vite.config.js
      - ${PWD}/../../apps/front/index.html:/usr/src/apps/front/index.html
    environment:
      - NODE_ENV=development
    networks:
      - lnmarkets_umbrel_testnet
